### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by benoliver999** [chrisandchris/barcode-bundle#1]
Would it be possible to get this bundle working on Symfony 4? From what I can tell it would just need a composer.json upgrade - I'm not seeing any deprecation warnings related to it.

**Comment by chrisandchris** [comment]
Should be possible, I didn't test it and I didn't use the bundle for quite some time. Would you mind creating a PR?

**Comment by benoliver999** [comment]
On 18-02-26 12:53:47, Christian wrote:
>Should be possible, I didn't test it and I didn't use the bundle for quite some time. Would you mind creating a PR?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chrisandchris/barcode-bundle/issues/1#issuecomment-368491695

If I get a few minutes I'll set up a Symfony 4 test and see if it works.  

I tried earlier but kept getting class not found errors - didn't have 
time to sort it out so I'll try again later.

**Comment by benoliver999** [comment]
Did it in #2

**Comment by benoliver999** [comment]
Right, sorry for all the spam. It's done now, I promise!

**Comment by chrisandchris** [comment]
Haha xD It's allright, thank you very much. I just merged the PR and created a v2 release out of it. I also allowed myself to update the license to Apache 2.0, as it is less restrictive.
